### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by religofsil** [catebi/FreeganBot#18]

**Comment by religofsil** [comment]
кроме очевидных пакетов, которые есть в коде, есть как минимум неочевидный pymorphy3 (нужен для работы лемматизатора spacy, но только для русского языка), без которого код в чистом окружении не заведётся и не скажет, почему сломался

**Comment by lejafo** [comment]
а есть для питона что-то вроде package.json и пакетного менеджера в довесок (аля npm)? чтобы выписать все зависимости и скопом их все установить через кли?

**Comment by religofsil** [comment]
> а есть для питона что-то вроде package.json и пакетного менеджера в довесок (аля npm)? чтобы выписать все зависимости и скопом их все установить через кли?

файл requirements.txt собирается как раз для того, чтобы можно было сделать `pip install requirements.txt`
