### ISSUE TITLE
Добавить тестовый корпус сообщений

### ISSUE THREAD

**Issue by religofsil** [catebi/FreeganBot#24]
UPD

Сохранять все сообщения через post-метод в catebi.api 

`https://api.catebi.ge/api/Freegan/SaveMessage`

Взять ~100 сообщений из чата с мисс марпл, разметить релевантные и нерелевантные, оценить текущую [F-меру](https://en.wikipedia.org/wiki/F-score). Потом будем перед мёрджем проверять, что новые правила её не роняют.

**Comment by lejafo** [comment]
это хорошо вписалось бы в continuous integration. чтобы оно само пробегалось по подготовленному пулу сообщений всякий раз при мердже в мейн

**Comment by religofsil** [comment]
Ага, это план.

**Comment by religofsil** [comment]
Что делать:

1. зайти в [freegan_catebi_leshiy_chat](https://t.me/freegan_catebi_leshiy_chat)
2. скопипастить оттуда в первый столбик таблички (google sheets, excel, что угодно) 100 сообщений, на которых мы хотим проверять качество обработки сообщений
3. поставить в колонке справа напротив каждого сообщения 1, если оно релевантно (там есть товары для животных), и 0, если оно нерелевантно (там нет товаров для животных)
4. выгрузить файл в репозиторий в формате `.csv` или `.tsv`
